networks:
  library-network:
    driver: bridge
    
services:
  webapi:
    image: library.webapi
    build:
      context: .
      dockerfile: Library.WebApi/Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    container_name: library_webapi
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=pg_db;Port=5432;Database=lib_db;Username=postgres;Password=123;Pooling=true;
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SecurePassword
    networks:
      - library-network
    depends_on:
      pg_db:
        condition: service_healthy
    restart: on-failure
    
  pg_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lib_db
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: library_postgres_db
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  db_data: