services:    
  pg_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lib_db
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: library_postgres_db
    networks:
      - lib_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: library_redis
    networks:
      - lib_network

networks:
  lib_network:
    driver: bridge
    
volumes:
  db_data: